steps:
  # Build container
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', './' ]

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  # Deployment hook must define:
  # _SERVICE_NAME, _REGION, _BUCKET, _UPLOAD_CHUNK_IN_MB, _SERVICE_ACCOUNT_EMAIL
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
      - '--update-env-vars'
      - 'BUCKET=$_BUCKET,UPLOAD_CHUNK_IN_MB=$_UPLOAD_CHUNK_IN_MB'
      - '--service-account'
      - '$_SERVICE_ACCOUNT_EMAIL'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
