version: "3.7"

services:

  gcs-upload:
    container_name: ${_SERVICE_NAME}
    build: ./
    image: ${_SERVICE_NAME}:latest
    #read_only: true
    environment:
      - PORT=${_PORT}
      - BUCKET=${_BUCKET}
      - GOOGLE_APPLICATION_CREDENTIALS=${_CREDENTIALS_PATH}
      - UPLOAD_CHUNK_IN_MB=${_UPLOAD_CHUNK_IN_MB}
    volumes:
      - ${_CREDENTIALS_NAME}:${_CREDENTIALS_PATH}:ro
    ports:
      - "${_PORT}:${_PORT}"
